// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql_trainee3

const TableNameDSActivity = "DS_Activity"

// DSActivity mapped from table <DS_Activity>
type DSActivity struct {
	ID   int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	Name string `gorm:"column:Name;not null" json:"Name"`
	Open bool   `gorm:"column:Open;not null" json:"Open"`
}

// TableName DSActivity's table name
func (*DSActivity) TableName() string {
	return TableNameDSActivity
}
