// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql_trainee3

const TableNameDSReward = "DS_Rewards"

// DSReward mapped from table <DS_Rewards>
type DSReward struct {
	ID         int32  `gorm:"column:Id;primaryKey;autoIncrement:true" json:"Id"`
	ActivityID int32  `gorm:"column:ActivityId;not null" json:"ActivityId"`
	Weight     int32  `gorm:"column:weight;not null" json:"weight"`
	Rewards    string `gorm:"column:Rewards;not null" json:"Rewards"`
}

// TableName DSReward's table name
func (*DSReward) TableName() string {
	return TableNameDSReward
}
