// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mysql_trainee3

const TableNameMember = "Member"

// Member mapped from table <Member>
type Member struct {
	MemberID int32  `gorm:"column:MemberId;primaryKey;autoIncrement:true" json:"MemberId"`
	Name     string `gorm:"column:Name;not null" json:"Name"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
